server:
  port: 8091

spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5532/url
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update